### ISSUE TITLE
코드정리 및 매거진 수정

### ISSUE THREAD

**Issue by Sangreal2021** [tjoeunoff/there#45]
## 코드 정리 및 매거진 수정
<br />

###  추가사항

1) 코드 정리
2) 매거진 해시태그 모양 장소게시글과 일치
<br /> 
 
### 수정사항 또는 수정예정인것들

1) json관련 추가 예정
2) 쿠키 관련 추가 예정
3) 포트폴리오 작성 예정
4) 스토리보드 작성 예정
<br />

**Comment by tjoeunoff** [comment]
완료
